config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'city_search', to: 'home#search'

  get '/dark_mode', to: 'application#dark_mode', as: 'dark_mode'
  get '/light_mode', to: 'application#light_mode', as: 'light_mode'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def dark_mode
    cookies[:dark_mode] = {
      value: 'dark mode on'
    }
    redirect_to root_path
  end

  def light_mode
    cookies.delete(:dark_mode)
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'json'

  def index; end

  def search
    location = params[:query]
    pull_api_data_and_parse(location)
    render :index
  end

  private

  def pull_api_data_and_parse(location)
    api_key = ENV['WEATHER_API_KEY']
    url = "https://api.openweathermap.org/data/2.5/weather?q=#{location}&appid=#{api_key}&units=metric"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)
    handle_errors(data)
  end

  def handle_errors(data)
    if data['id']
      split_data(data)
    else
      flash.now[:alert] = 'Could not find location, please check spelling and try again.'
    end
  end

  def split_data(data)
    name(data)
    weather(data)
    main(data)
    sunrise_sunset(data)
    minor(data)
    time_at_location(data)
  end

  def name(data)
    @city = data['name']
  end

  def weather(data)
    @weather = data['weather'][0]['main']
    @description = data['weather'][0]['description']
  end

  def main(data)
    @temperature = data['main']['temp'].round
    @temp_min = data['main']['temp_min'].round
    @temp_max = data['main']['temp_max'].round
    @pressure = data['main']['pressure'].round
    @humidity = data['main']['humidity'].round
  end

  def sunrise_sunset(data)
    sunrise = Time.at(data['sys']['sunrise']).utc + data['timezone'].seconds
    sunset = Time.at(data['sys']['sunset']).utc + data['timezone'].seconds

    @sunrise = sunrise.to_s(:time)
    @sunset = sunset.to_s(:time)
  end

  def minor(data)
    @visibility = data['visibility']
    @wind_speed = data['wind']['speed'].round
  end

  def time_at_location(data)
    time_at_location = Time.now.utc + data['timezone'].seconds if data['timezone'].seconds
    @time_at_location = time_at_location.to_s(:time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='app'>
  <div class='button_container'>
    <% if cookies[:dark_mode] %>
      <%= button_to 'Light Mode', light_mode_path, method: :get, class: 'button' %>
    <% else %>
      <%= button_to 'Dark Mode', dark_mode_path, method: :get, class: 'button'%>
    <% end %>
  </div>

  <div class='search'>
    <form action='city_search' method='get' accept-charset='UTF-8' >
      <input id='query' name='query' type='text' placeholder='Enter Location' />
    </form>
  </div>
  <% if flash[:alert] %>
    <div id="alert" class='alert'>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class='container'>
    <div class='main'>
      <div class='city'>
        <p><%= @city %></p>
      </div>
      <div class='temp_and_time'>
        <h1><%= @temperature %>°C</h1>
        <h1><%= @time_at_location %></h1>
      </div>
      <div class='weather'>
        <p><%= @weather %></p>
      </div>
      <div class='description'>
        <p><%= @description %></p>
      </div>
    </div>

    <div class='secondary'>
      <div class='temp_min'>
        <p class='bold'><%= @temp_min %>°C</p>
        <p> Min Temp </p>
      </div>
      <div class='temp_max'>
        <p class='bold'><%= @temp_max %>°C</p>
        <p> Max Temp </p>
      </div>
      <div class='sunrise'>
        <p class='bold'><%= @sunrise %></p>
        <p> Sunrise </p>
      </div>
      <div class='sunset'>
        <p class='bold'><%= @sunset %></p>
        <p> Sunset </p>
      </div>
    </div>

    <div class='tertiary'>
      <div class='wind_speed'>
        <p class='bold'><%= @wind_speed %> m/s</p>
        <p> Wind Speed </p>
      </div>
      <div class='humidity'>
        <p class='bold'><%= @humidity %>%</p>
        <p> Humidity </p>
      </div>
      <div class='pressure'>
        <p class='bold'><%= @pressure %> hPa</p>
        <p> Pressure </p>
      </div>
      <div class='visibility'>
        <p class='bold'><%= @visibility %> m</p>
        <p> Visibility </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <% if cookies[:dark_mode] %>
      <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>